version: "3.9"

services:
  api-key-notifier:
    build:
      context: .
      dockerfile: Dockerfile
    image: expired_key_notifier:latest
    container_name: expired_key_notifier_worker
    env_file: .env
    environment:
      MONGO_HOST_MAIN: "${MONGO_HOST_MAIN}"
      MONGO_PORT_MAIN: "${MONGO_PORT_MAIN}"
      MONGO_USER_MAIN: "${MONGO_USER_MAIN}"
      MONGO_PASSWORD_MAIN: "${MONGO_PASSWORD_MAIN}"
    volumes:
      - "./cron/cron.log:/var/log/cron.log"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: unless-stopped